### ISSUE TITLE
Useless for attacks from the real guys

### ISSUE THREAD

**Issue by AlfreditoN** [dennorske/samp-packet-proxy#12]
Just letting you know that this only works for attacks from script kiddies with a cheap $3 spoofing machine that barely hits 50Mbp/s or less. Under load of attacks from the real guys (e.g. > 300Mbp/s or 50 Mpps - btw M = Million) this just hangs up, as the amount of available ports (40000 - 65535) used in the binding that receives-replies to the packets is reduced to 0.

I will not reveal my identity but you need to do some research and get real dirty (this is just an easy workaround as I've explained above) if you want something working for the real guys. Alternatively contact someone who already has the solution in-place ;)

Anyway, nice try.

Cheers.

**Comment by dennorske** [comment]
...In that case people should consider proper firewalls. 
This code helped a lot of people back in 2019, as there are mostly just young people trying to ruin for others, which just buy a service online to target the query mechanism.

Please read the read-me of this project to understand what my code does do, and what it does not do. It is not stopping or filtering the attack, it is _accelerating the rate at which the server can respond to queries_. 
I am well aware of the limitations a high level language like Python has, and that it starts to struggle around 7-10k PPS.

I don't need your identity- happy Easter!
