### ISSUE TITLE
Issues running script

### ISSUE THREAD

**Issue by Chaprnks** [dennorske/samp-packet-proxy#8]
After completing the iptables rules, I go to run the python3 script; here's what it returns:

```
root@dedi:/home# python3 packet-proxy.py
Listening on port 7778 for server 158.69.121.201 on port 7777
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "packet-proxy.py", line 78, in querythread
    clients = self.sock.recv(1024)[11:]
socket.timeout: timed out
```

![YyRfQKR](https://user-images.githubusercontent.com/6340970/79927294-4da01700-840d-11ea-9d8e-b1ad3426e605.png)

**Comment by dennorske** [comment]
Looks like it has issues creating a socket for the specified port. Have you made sure that 7778 and 7777 is free to use, ans that the firewall is not doing anything with it?

May I also see your rules (run iptables-save) and your configuration in the code
Den
